baseurl = "127.0.0.1:1313/"
languageCode = "ru-ru"
title = "VK320"
canonifyurls = false
copyright = "<a href='http://romansilin.com' target='_blank'>Roman Silin</a>"

[params]
  logo = "/images/logo.png"